#!/usr/bin/env bash
set -e
# TODO: Make interruptible/atomic
# TODO: Use correct ssh port? (can change over a deploy)
HOST=root@138.68.83.114

SSH_OPTS="-o BatchMode=yes"

# TODO: What about GC?

# TODO: Generate hardware-config every time?

echo "Building system.."
SYSTEM=$(nix-build --no-out-link -A system)

echo "Copying closure to host.."
nix-copy-closure -s --to ssh://$HOST $SYSTEM

echo "Triggering system switcher.."
id=$(ssh $SSH_OPTS $HOST switch start $SYSTEM)


echo "Trying to confirm success.."
set +e
prevstatus="unknown"
prevactive=0
active=1
while [ "$active" != 0 ]; do
	status=$(timeout 5 ssh -o ControlPath=none $SSH_OPTS $HOST switch active "$id")
	active=$?
	sleep 1
done

case "$status" in
	"success")
		echo "Successfully activated new system!"
		;;
	"failure")
		echo "Failed to activate new system! Rolled back to previous one"
		;;
	*)
	  echo "This shouldn't occur!"
		;;
esac
